# VirtualBox
Vagrant.configure("2") do |config|
  config.vm.define "build-raid" do |sub|
    sub.vm.box = "ubuntu/trusty64"
    # sub.vm.box = "centos/7"
    sub.vm.hostname = "build-raid"
    # sub.vm.network :private_network, ip: "192.168.50.11"
    sub.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end
end